GEMINI_API_KEY = "AIzaSyCo1TgO60NwadRjwit5Qhc4CmschHsRsCE"
SUPABASE_URL = "https://bnoqwspryddlpdhxudkq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJub3F3c3ByeWRkbHBkaHh1ZGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NTM0MzcsImV4cCI6MjA3NzQyOTQzN30.Li7RW8xRRQQ-05vWVei1h1KLmehL-qzoEpqIQi5_Y1c"